#!/bin/bash

clear

service_name=senti-eventbroker.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/services/eventbroker/production

service=$service_dir/$service_name

echo Registering Senti Event Broker service for production ...


if [ ! -e "$service" ]; then
	echo
    echo "Senti Event Broker service is not installed"
	echo "Installing Senti Event Broker service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else 
    echo "Senti Event Broker service is already installed"
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi 